EShop/Areas/Admin/Controllers/AdminBrandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TMDTShop.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using System.Globalization;
using System.IO;
using TMDTShop.Helpper;
using PagedList.Core;

namespace TMDTShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminBrandsController : Controller
    {
        private readonly EcommerceVer2Context _context;
        public static string image;
        public INotyfService _notyfService { get; }
        public AdminBrandsController(EcommerceVer2Context context, INotyfService notyfService)
        {
            _notyfService = notyfService;
            _context = context;
        }

        // GET: Admin/AdminBrands
        public IActionResult Index(string sortOrder, string currentFilter, string searchStr, int? page)
        {
            var _brand = from m in _context.Brands select m;
            //Sort
            ViewData["IdSortParm"] = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewData["NameSortParm"] = sortOrder == "Name" ? "name_desc" : "Name";
            switch (sortOrder)
            {
                case "id_desc":
                    _brand = _brand.OrderByDescending(p => p.BrandId);
                    break;
                case "Name":
                    _brand = _brand.OrderBy(p => p.BrandName);
                    break;
                case "name_desc":
                    _brand = _brand.OrderByDescending(p => p.BrandName);
                    break;
                default:
                    _brand = _brand.OrderBy(p => p.BrandId);
                    break;
            }

            //Search
            ViewData["CurrentFilter"] = searchStr;
            if (!String.IsNullOrEmpty(searchStr))
            {
                _brand = _brand.Where(p => p.BrandId.ToString().Contains(searchStr) || p.BrandName.Contains(searchStr));
            }

            //Paginate
            var pageNo = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 5;
            ViewBag.CurrentPage = pageNo;
            PagedList<Brand> models = new PagedList<Brand>(_brand, pageNo, pageSize);
            return View(models);
        }

        // GET: Admin/AdminBrands/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .FirstOrDefaultAsync(m => m.BrandId == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // GET: Admin/AdminBrands/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminBrands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BrandId,BrandName,Logo")] Brand brand, Microsoft.AspNetCore.Http.IFormFile fLogo)
        {
            if (ModelState.IsValid)
            {
                var _brand = from m in _context.Brands select m;
                if (_brand.Any(a => a.BrandName == brand.BrandName))
                {
                    _notyfService.Error("Nhãn hàng này đã có trong Cơ sở dữ liệu!");
                    return RedirectToAction(nameof(Create));
                }
                else
                {
                    brand.BrandName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(brand.BrandName);
                    if (fLogo != null)
                    {
                        string extennsion = Path.GetExtension(fLogo.FileName);
                        image = Utilities.ToUrlFriendly(brand.BrandName) + extennsion;
                        brand.Logo = await Utilities.UploadFile(fLogo, @"brands", image.ToLower());
                    }
                    if (string.IsNullOrEmpty(brand.Logo)) brand.Logo = "thumb-6.jpg";
                    _notyfService.Success("Thêm thành công!");
                    _context.Add(brand);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(brand);
        }

        // GET: Admin/AdminBrands/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands.FindAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        // POST: Admin/AdminBrands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BrandId,BrandName,Logo")] Brand brand, Microsoft.AspNetCore.Http.IFormFile fLogo)
        {
            if (id != brand.BrandId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var _brand = from m in _context.Brands select m;
                    if (_brand.Any(a => a.BrandName == brand.BrandName && a.Logo == brand.Logo))
                    {
                        _notyfService.Error("Nhãn hàng này đã có trong Cơ sở dữ liệu!");
                        return RedirectToAction(nameof(Edit));
                    }
                    else
                    {
                        brand.BrandName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(brand.BrandName);
                        if (fLogo != null)
                        {
                            string extennsion = Path.GetExtension(fLogo.FileName);
                            image = Utilities.ToUrlFriendly(brand.BrandName) + extennsion;
                            brand.Logo = await Utilities.UploadFile(fLogo, @"brands", image.ToLower());
                        }
                        if (string.IsNullOrEmpty(brand.Logo)) brand.Logo = "thumb-6.jpg";
                        _notyfService.Success("Sửa thành công!");
                        _context.Update(brand);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.BrandId))
                    {
                        _notyfService.Error("Lỗi!!!!!!!!!!!!!");
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Admin/AdminBrands/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .FirstOrDefaultAsync(m => m.BrandId == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // POST: Admin/AdminBrands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brand = await _context.Brands.FindAsync(id);
            _context.Brands.Remove(brand);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrandExists(int id)
        {
            return _context.Brands.Any(e => e.BrandId == id);
        }
    }
}

EShop/Areas/Admin/Views/AdminBrands/Create.cshtml
@model TMDTShop.Models.Brand

@{
    ViewData["Title"] = "Tạo nhãn";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="main-content">
    <form asp-controller="AdminBrands" asp-action="Create" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="page-header no-gutters has-tab">
            <div class="d-md-flex m-b-15 align-items-center justify-content-between">
                <div class="media align-items-center m-b-15">
                    <div class="avatar avatar-image rounded" style="height: 165px; width: 165px">
                        <img src="~/images/brands/thumb-16.jpg" alt="" id="output" style="border-radius:20px;">
                    </div>
                    <div class="m-l-15">
                        <h4 class="m-b-0">Unknown</h4>
                        <p class="text-muted m-b-0">ID: #Unknown</p>
                    </div>
                </div>
                <div class="m-b-15">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">
                            <i class="anticon anticon-save"></i>
                            <span>Tạo</span>
                        </button>
                    </div>
                    <div>
                        <a asp-action="Index" class="btn btn-dark">Back to List</a>
                    </div>
                </div>
            </div>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin cơ bản</a>
                </li>
            </ul>
        </div>
        <div class="tab-content m-t-15">
            <div class="tab-pane fade show active" id="product-edit-basic">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="BrandName" class="control-label">Tên nhãn hàng</label>
                            <input asp-for="BrandName" class="form-control" />
                            <span asp-validation-for="BrandName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Logo" class="font-weight-semibold">Upload Ảnh</label>
                            <input type="file" name="fLogo" asp-for="Logo" class="form-control-file" onchange="loadFile(event)" />
                            <span asp-validation-for="Logo" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EShop/Areas/Admin/Views/AdminBrands/Delete.cshtml
@model TMDTShop.Models.Brand

@{
    ViewData["Title"] = "Xóa nhãn hàng Id #" + Model.BrandId;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div style="margin-top:10%; margin-left:10%;">
    <h3>M có chắc là m muốn xóa nó không</h3>
    <div>
        <h4>Nhãn hàng</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                Tên nhãn hàng
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BrandName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Logo)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Logo)
            </dd>
        </dl>
        <div class="profile-img">
            <img src="~/images/User/@Model.Logo" alt="@Model.BrandName" />
            @*<div class="file btn btn-lg btn-primary">
                Change Photo
                <input type="file" name="file" />
            </div>*@
        </div>
        <div>

        </div>

        <form asp-action="Delete" style="margin-top: 30px;">
            <input type="hidden" asp-for="BrandId" />
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalCenter">
                Xóa
            </button>  |
            <a asp-action="Index">Trở về</a>
        </form>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Xác nhận xóa</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <i class="anticon anticon-close"></i>
                </button>
            </div>
            <div class="modal-body">
                Bạn có chắc muốn xóa ?
            </div
            <div class="modal-footer">
                <form asp-action="Delete">
                    <button type="button" class="btn btn-default" data-dismiss="modal"> NO </button>
                    <input type="submit" value="Xóa" class="btn btn-danger" />
                </form>
            </div>
        </div>
    </div>
</div>
@section Styles {
    <style>
        .profile-img img {
            /*width: 100%;
            height: 100%;*/
            max-height: 188px;
            max-width: 125px;
            border-radius: 10px;
        }
    </style>
}

EShop/Areas/Admin/Views/AdminBrands/Details.cshtml
@model TMDTShop.Models.Brand

@{
    ViewData["Title"] = "Chi tiết nhãn hàng #" +Model.BrandId;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-content">
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
                @*<div class="avatar avatar-image rounded" style="height: 70px; width: 70px">
                        <img src="~/images/categoties/@Model.ThumbImg" alt="@Model.Title">
                    </div>*@
                <div class="m-l-15">
                    <h4 class="m-b-0">@Model.BrandName</h4>
                    <p class="text-muted m-b-0">ID: @Model.BrandId</p>
                </div>
            </div>
            <div class="m-b-15">
                <div class="form-group">
                    <a asp-controller="AdminBrands" asp-action="Edit" asp-route-id="@Model.BrandId" class="btn btn-primary">
                        <i class="anticon anticon-edit"></i>
                        <span>Sửa</span>
                    </a>
                </div>
                <div>
                    <a asp-action="Index" type="button" class="btn btn-dark">Trở về</a>
                </div>
            </div>
        </div>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.BrandName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BrandName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Logo)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Logo)
            </dd>
        </dl>
    </div>
</div>

EShop/Areas/Admin/Views/AdminBrands/Edit.cshtml
@model TMDTShop.Models.Brand

@{
    ViewData["Title"] = "Chỉnh sửa nhãn hàng #"+Model.BrandId;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-content">
    <form asp-controller="AdminBrands" asp-action="Edit" asp-route-id="@Model.BrandId" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="BrandId" />
        <input type="hidden" asp-for="Logo" />
        <div class="page-header no-gutters has-tab">
            <div class="d-md-flex m-b-15 align-items-center justify-content-between">
                <div class="media align-items-center m-b-15">
                    <div class="avatar avatar-image rounded" style="height: 165px; width: 165px">
                        <img src="~/images/brands/@Model.Logo"   id="output">
                    </div>
                    <div class="m-l-15">
                        <h4 class="m-b-0">@Model.BrandName</h4>
                        <p class="text-muted m-b-0">ID: #@Model.BrandId</p>
                    </div>
                </div>
                <div class="m-b-15">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">
                            <i class="anticon anticon-save"></i>
                            <span>Lưu</span>
                        </button>
                    </div>
                    <div>
                        <a asp-action="Index" type="button" class="btn btn-dark">Trở về</a>
                    </div>
                </div>
            </div>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin cơ bản</a>
                </li>
            </ul>
        </div>
        <div class="tab-content m-t-15">
            <div class="tab-pane fade show active" id="product-edit-basic">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="BrandName" class="control-label">Tên nhãn hàng</label>
                            <input asp-for="BrandName" class="form-control" />
                            <span asp-validation-for="BrandName" class="text-danger"></span>
                        </div>
                        @*<div class="form-group">
                            <label asp-for="Logo" class="font-weight-semibold">Upload Ảnh</label>
                            <input type="file" name="fThumbImg" asp-for="Logo" class="form-control-file" onchange="loadFile(event)" />
                            <span asp-validation-for="Logo" class="text-danger"></span>
                        </div>*@
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EShop/Areas/Admin/Views/AdminBrands/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<TMDTShop.Models.Brand>

@{
    int _current = ViewBag.CurrentPage;
    ViewData["Title"] = "Nhãn hàng";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="main-content">
    <div class="page-header">
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
                <span class="breadcrumb-item active">Quản lý thương hiệu</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row m-b-30">
                <div class="col-lg-8">
                    <form asp-controller="AdminBrands" asp-action="Index">
                        <p>
                            <input type="search" name="searchStr" value="@ViewData["CurrentFilter"]" required />
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </p>
                    </form>
                </div>

                <div class="col-lg-4 text-right">
                    <a asp-controller="AdminBrands" asp-action="Create" class="btn btn-primary">
                        <i class="anticon anticon-plus-circle m-r-5"></i>
                        <span>Thêm thương hiệu</span>
                    </a>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover e-commerce-table">
                    <thead>
                        <tr>
                            <th>
                                <a asp-action="Index" asp-route-sortOrder="@ViewData["IdSortParm"]">
                                    ID
                                </a>
                            </th>
                            <th>
                                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]">
                                    Tên thương hiệu
                                </a>
                            </th>
                            <th>Logo</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @item.BrandId
                                    </td>
                                    <td>
                                        <div class="d-flex align-items-center text-center">
                                            @*<img class="img-fluid rounded" src="~/images/categories/@item.ThumbImg"
                                                style="max-width: 60px" alt="">*@
                                            <h6 class="m-b-0 m-l-10">@item.BrandName</h6>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="d-flex align-items-center text-center">
                                            <img class="img-fluid rounded" src="~/images/brands/@item.Logo"
                                                 style="max-width: 60px" alt="">
                                        </div>
                                    </td>
                                    <td>
                                        <a asp-controller="AdminBrands" asp-action="Details" asp-route-id="@item.BrandId" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <i class="anticon anticon-eye"></i>
                                        </a>
                                        <a asp-controller="AdminBrands" asp-action="Edit" asp-route-id="@item.BrandId" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <i class="anticon anticon-edit"></i>
                                        </a>
                                        <a asp-controller="AdminBrands" asp-action="Delete" asp-route-id="@item.BrandId" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <i class="anticon anticon-delete"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
                <pager class="paper-container" list="@Model" asp-area="Admin" asp-controller="AdminBrands" asp-action="Index"></pager>
            </div>
        </div>
    </div>
</div>


@section Styles {
    <style>
        form {
            position: relative;
            transform: translate(5%,5%);
            transition: all 1s;
            width: 50px;
            height: 50px;
            background: white;
            box-sizing: border-box;
            border-radius: 25px;
            border: 4px solid black;
            padding: 5px;
        }

            form input {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 42.5px;
                line-height: 30px;
                outline: 0;
                border: 0;
                display: none;
                font-size: 1em;
                border-radius: 20px;
                padding: 0 20px;
                background: #CBF6D2;
            }

        .fa {
            box-sizing: border-box;
            padding: 10px;
            width: 42.5px;
            height: 42.5px;
            position: absolute;
            top: 0;
            right: 0;
            border-radius: 50%;
            color: #07051a;
            text-align: center;
            font-size: 1.2em;
            transition: all 1s;
        }

        form:hover,
        form:valid {
            width: 200px;
            cursor: pointer;
        }

            form:hover input,
            form:valid input {
                display: block;
            }

            form:hover .fa,
            form:valid .fa {
                background: #07051a;
                color: white;
            }

        button {
            border: none;
        }
    </style>
  <link href="~/AdminAssets/vendors/datatables/dataTables.bootstrap.min.css" rel="stylesheet">
}