EShop/Areas/Admin/Controllers/AdminTransactStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TMDTShop.Models;
using Microsoft.AspNetCore.Authorization;

namespace TMDTShop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class AdminTransactStatusController : Controller
    {
        private readonly EcommerceVer2Context _context;

        public AdminTransactStatusController(EcommerceVer2Context context)
        {
            _context = context;
        }

        // GET: Admin/AdminTransactStatus
        public async Task<IActionResult> Index()
        {
            return View(await _context.TransactStatuses.ToListAsync());
        }

        // GET: Admin/AdminTransactStatus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transactStatus = await _context.TransactStatuses
                .FirstOrDefaultAsync(m => m.TransactionStatusId == id);
            if (transactStatus == null)
            {
                return NotFound();
            }

            return View(transactStatus);
        }

        // GET: Admin/AdminTransactStatus/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminTransactStatus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TransactionStatusId,Status,Descriptions")] TransactStatus transactStatus)
        {
            if (ModelState.IsValid)
            {
                _context.Add(transactStatus);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(transactStatus);
        }

        // GET: Admin/AdminTransactStatus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transactStatus = await _context.TransactStatuses.FindAsync(id);
            if (transactStatus == null)
            {
                return NotFound();
            }
            return View(transactStatus);
        }

        // POST: Admin/AdminTransactStatus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TransactionStatusId,Status,Descriptions")] TransactStatus transactStatus)
        {
            if (id != transactStatus.TransactionStatusId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(transactStatus);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransactStatusExists(transactStatus.TransactionStatusId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(transactStatus);
        }

        // GET: Admin/AdminTransactStatus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transactStatus = await _context.TransactStatuses
                .FirstOrDefaultAsync(m => m.TransactionStatusId == id);
            if (transactStatus == null)
            {
                return NotFound();
            }

            return View(transactStatus);
        }

        // POST: Admin/AdminTransactStatus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var transactStatus = await _context.TransactStatuses.FindAsync(id);
            _context.TransactStatuses.Remove(transactStatus);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TransactStatusExists(int id)
        {
            return _context.TransactStatuses.Any(e => e.TransactionStatusId == id);
        }
    }
}

EShop/Areas/Admin/Views/AdminTransactStatus/Create.cshtml
@model TMDTShop.Models.TransactStatus

@{
    ViewData["Title"] = "Tạo trạng thái";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div style="margin-left:10% ;margin-top:10%">
    <h1>Tạo mới</h1>

    <h4>Trạng thái</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Status" class="control-label"></label>
                    <input asp-for="Status" class="form-control" />
                    <span asp-validation-for="Status" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Descriptions" class="control-label"></label>
                    <input asp-for="Descriptions" class="form-control" />
                    <span asp-validation-for="Descriptions" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Tạo mới" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Trở về</a>
    </div>


</div>

EShop/Areas/Admin/Views/AdminTransactStatus/Delete.cshtml
@model TMDTShop.Models.TransactStatus

@{
    ViewData["Title"] = "Xóa trạng thái";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div style="margin-top: 10%; margin-left: 10%">
    <h1>Xóa</h1>

    <h3>Chắc chứ?</h3>
    <div>
        <h4>TransactStatus</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Status)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Status)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Descriptions)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Descriptions)
            </dd>
        </dl>
        <form asp-action="Delete">
            <input type="hidden" asp-for="TransactionStatusId" />
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalCenter">
                Xóa trạng thái
            </button>
            <a asp-action="Index" type="button" class="btn btn-dark">Trở về</a>
        </form>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">Xác nhận xóa</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <i class="anticon anticon-close"></i>
                    </button>
                </div>
                <div class="modal-body">
                    Bạn có muốn xóa ???
                </div>
                <div class="modal-footer">
                    <form asp-action="Delete">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                        <input type="submit" value="Xóa" class="btn btn-danger" />
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

EShop/Areas/Admin/Views/AdminTransactStatus/Details.cshtml
@model TMDTShop.Models.TransactStatus

@{
    ViewData["Title"] = "Chi tiết trạng thái #"+Model.TransactionStatusId;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card" style="border-radius: 1rem; margin-top:10%;margin-left:10%; margin-right:10%">
    <div class="card-header">
        <h3 class="card-title">Thông tin trạng thái</h3>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0" style="height: 300px;">
            <table class="table table-head-fixed text-nowrap">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><span class="tag tag-success">@Model.TransactionStatusId</span></td>
                    </tr>
                    <tr>
                        <td>Tên Quyền</td>
                        <td><span class="tag tag-success">@Model.Status</span></td>
                    </tr>
                    <tr>
                        <td>Mô Tả</td>
                        <td><span class="tag tag-success">@Model.Descriptions</span></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
    <div>
        <a class="btn btn-adn fas fa-arrow-alt-circle-left btn-secondary" asp-action="Index"><span style="margin-left:10px;">Trở về</span></a> |
        <a class="btn btn-adn fa fa-edit btn-primary" asp-action="Edit" asp-route-id="@Model.TransactionStatusId"><span style="margin-left:10px;">Chỉnh sửa</span></a>
    </div>
</div>

EShop/Areas/Admin/Views/AdminTransactStatus/Edit.cshtml
@model TMDTShop.Models.TransactStatus

@{
    ViewData["Title"] = "Chỉnh sửa trạng thái #"+Model.TransactionStatusId;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div style="margin-top: 10%; margin-left: 10%;">
    <h1>Chỉnh sửa</h1>

    <h4>Trạng thái</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="TransactionStatusId" />
                <div class="form-group">
                    <label asp-for="Status" class="control-label"></label>
                    <input asp-for="Status" class="form-control" />
                    <span asp-validation-for="Status" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Descriptions" class="control-label"></label>
                    <input asp-for="Descriptions" class="form-control" />
                    <span asp-validation-for="Descriptions" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Trở về</a>
    </div>


</div>

EShop/Areas/Admin/Views/AdminTransactStatus/Index.cshtml
@model IEnumerable<TMDTShop.Models.TransactStatus>

@{
    ViewData["Title"] = "Quản Lý Trạng Thái Đơn Hàng";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div style="margin-top:10%">
    <h1>Quản lý trạng thái</h1>
    <a asp-area="Admin" asp-controller="AdminTransactStatus" asp-action="Create" class="btn btn-block btn-outline-success btn-sm"><i class="fas fa-user-plus" style="margin-right:10px;"></i>Create New</a>
    <!--Start Designed Table // Material-Kit-->
    <div class="card" style="margin-top:50px;">
        <div class="table-responsive">
            <table class="table align-items-center mb-0">
                <thead>
                    <tr>
                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">ID</th>
                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                            Status
                        </th>
                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                            Descriptions
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <div class="d-flex px-2">
                                        <div class="my-auto">
                                            <h6 class="mb-0 text-xs">@item.TransactionStatusId</h6>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <p class="text-xs font-weight-normal mb-0">@item.Status</p>
                                </td>
                                <td>
                                    <span class="badge badge-dot me-4">
                                        @*<i class="bg-info"></i>*@
                                        <span class="text-dark text-xs">@item.Descriptions</span>
                                    </span>
                                </td>

                                <td class="align-middle">
                                    <a asp-area="Admin" asp-controller="AdminTransactStatus" asp-action="Details" asp-route-id="@item.TransactionStatusId" class="btn btn-outline-info btn-block btn-sm"><i class="fas fa-info-circle"></i> Xem</a>
                                </td>
                                <td class="align-middle">
                                    <a asp-area="Admin" asp-controller="AdminTransactStatus" asp-action="Edit" asp-route-id="@item.TransactionStatusId" class="btn btn-outline-warning btn-block btn-sm"><i class="fas fa-edit"></i> Sửa</a>
                                </td>
                                <td class="align-middle">
                                    <a asp-area="Admin" asp-controller="AdminTransactStatus" asp-action="Delete" asp-route-id="@item.TransactionStatusId" class="btn btn-outline-danger btn-block btn-sm" )><i class="fas fa-trash"></i> Xóa</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    <!--End Designed Table-->
</div>